# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: version.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='version.proto',
  package='braiins.bos',
  syntax='proto3',
  serialized_options=b'Z5github.com/braiins/bos-plus-api/braiins/bos;bos_proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rversion.proto\x12\x0b\x62raiins.bos\"U\n\nApiVersion\x12\r\n\x05major\x18\x01 \x01(\x04\x12\r\n\x05minor\x18\x02 \x01(\x04\x12\r\n\x05patch\x18\x03 \x01(\x04\x12\x0b\n\x03pre\x18\x04 \x01(\t\x12\r\n\x05\x62uild\x18\x05 \x01(\t\"\x13\n\x11\x41piVersionRequest2]\n\x11\x41piVersionService\x12H\n\rGetApiVersion\x12\x1e.braiins.bos.ApiVersionRequest\x1a\x17.braiins.bos.ApiVersionB7Z5github.com/braiins/bos-plus-api/braiins/bos;bos_protob\x06proto3'
)




_APIVERSION = _descriptor.Descriptor(
  name='ApiVersion',
  full_name='braiins.bos.ApiVersion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='major', full_name='braiins.bos.ApiVersion.major', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='minor', full_name='braiins.bos.ApiVersion.minor', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='patch', full_name='braiins.bos.ApiVersion.patch', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pre', full_name='braiins.bos.ApiVersion.pre', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='build', full_name='braiins.bos.ApiVersion.build', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=115,
)


_APIVERSIONREQUEST = _descriptor.Descriptor(
  name='ApiVersionRequest',
  full_name='braiins.bos.ApiVersionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=136,
)

DESCRIPTOR.message_types_by_name['ApiVersion'] = _APIVERSION
DESCRIPTOR.message_types_by_name['ApiVersionRequest'] = _APIVERSIONREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ApiVersion = _reflection.GeneratedProtocolMessageType('ApiVersion', (_message.Message,), {
  'DESCRIPTOR' : _APIVERSION,
  '__module__' : 'version_pb2'
  # @@protoc_insertion_point(class_scope:braiins.bos.ApiVersion)
  })
_sym_db.RegisterMessage(ApiVersion)

ApiVersionRequest = _reflection.GeneratedProtocolMessageType('ApiVersionRequest', (_message.Message,), {
  'DESCRIPTOR' : _APIVERSIONREQUEST,
  '__module__' : 'version_pb2'
  # @@protoc_insertion_point(class_scope:braiins.bos.ApiVersionRequest)
  })
_sym_db.RegisterMessage(ApiVersionRequest)


DESCRIPTOR._options = None

_APIVERSIONSERVICE = _descriptor.ServiceDescriptor(
  name='ApiVersionService',
  full_name='braiins.bos.ApiVersionService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=138,
  serialized_end=231,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetApiVersion',
    full_name='braiins.bos.ApiVersionService.GetApiVersion',
    index=0,
    containing_service=None,
    input_type=_APIVERSIONREQUEST,
    output_type=_APIVERSION,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_APIVERSIONSERVICE)

DESCRIPTOR.services_by_name['ApiVersionService'] = _APIVERSIONSERVICE

# @@protoc_insertion_point(module_scope)
